version: '3.7'
services:
    webapp:
        build: ./phones-frontend 
        ports:
            - "3000:3000"
        command: ["yarn", "start"]
        depends_on:
            - api
        volumes: 
            - ./phones-frontend:/app
            - /app/node_modules
        stdin_open: true

    api:
        build: ./phones-backend 
        ports:
            - "8080:8080"
        command: sh -c "yarn populate && yarn start"
        depends_on:
            - database
        environment:
            - DB_URL='mongodb://database:27017/guidesmiths'
            - PORT=8080
        volumes: 
            - ./phones-backend:/app
            - /app/node_modules

    database:
        image: "mongo:3.6.17-xenial"
        ports:
            - "27018:27017"
