version: '3.7'
services:
    webapp:
        build:
          context: ./phones-frontend
          dockerfile: Dockerfile.prod
        ports:
            - "8000:8000"
        command: ["serve", "-p", "8000", "-s", "build", "-n"]
        depends_on:
            - api

    api:
        build:
          context: ./phones-backend
          dockerfile: Dockerfile.prod
        ports:
            - "8080:8080"
        command: sh -c "yarn populate && yarn serve"
        depends_on:
            - database
        environment:
            - DB_URL='mongodb://database:27017/guidesmiths'
            - PORT=8080

    database:
        image: "mongo:3.6.17-xenial"
        ports:
            - "27018:27017"
